export default {
  kaupassa: {
    name: 'Kaupassa',
    questions: [
      { answer: 'Omena', origin: 'Apple', instruction: null, enabled: true },
      { answer: 'Appelsiini', origin: 'Orange', instruction: null, enabled: true },
      { answer: 'Banaani', origin: 'Banana', instruction: null, enabled: true },
      { answer: 'Sitruuna', origin: 'Lemon', instruction: null, enabled: true },
      { answer: 'Mansikka', origin: 'Strawberry', instruction: null, enabled: true },
      { answer: 'Mustikka', origin: 'Blueberry', instruction: null, enabled: true },
      { answer: 'Puolukka', origin: 'Lingonberry', instruction: null, enabled: true },
      { answer: 'Vadelma', origin: 'Raspberry', instruction: null, enabled: true },
      { answer: 'Lihatuotteet', origin: 'Meat products', instruction: null, enabled: true },
      { answer: 'Jauhliha', origin: 'Grounded meat', instruction: null, enabled: true },
      { answer: 'Kinkku', origin: 'Ham', instruction: null, enabled: true },
      { answer: 'Broileri', origin: 'Chicken', instruction: null, enabled: true },
      { answer: 'Lihapyörykkä', origin: 'Meat ball', instruction: null, enabled: true },
      { answer: 'Muna', origin: 'Egg', instruction: null, enabled: true },
      { answer: 'Keitetty muna', origin: 'Boiled egg', instruction: null, enabled: true },
      { answer: 'Paistettu muna', origin: 'Fried egg', instruction: null, enabled: true },
      { answer: 'Kananmuna', origin: 'Chicken egg', instruction: null, enabled: true },
      { answer: 'Kala', origin: 'Fish', instruction: null, enabled: true },
      { answer: 'Maitotuotteet', origin: 'Dairy products', instruction: null, enabled: true },
      { answer: 'Voi', origin: 'Butter', instruction: null, enabled: true },
      { answer: 'Margariini', origin: 'Margarine', instruction: null, enabled: true },
      { answer: 'Juusto', origin: 'Cheese', instruction: null, enabled: true },
      { answer: 'Maito', origin: 'Milk', instruction: null, enabled: true },
      { answer: 'Viljatuotteet', origin: 'Cereal products', instruction: null, enabled: true },
      { answer: 'Jauhot', origin: 'Flour', instruction: null, enabled: true },
      { answer: 'Puuro', origin: 'Porridge', instruction: null, enabled: true },
      { answer: 'Riisi', origin: 'Rice', instruction: null, enabled: true },
      { answer: 'Makaroni', origin: 'Macaroni', instruction: null, enabled: true },
      { answer: 'Leipä', origin: 'Bread', instruction: null, enabled: true },
      { answer: 'Pulla', origin: 'Sweet bun', instruction: null, enabled: true },
      { answer: 'Kakku', origin: 'Cake', instruction: null, enabled: true },
      { answer: 'Keksi', origin: 'Biscuit', instruction: null, enabled: true },
      { answer: 'Vihannekset ja Juurekset', origin: 'Vegetables and Roots', instruction: null, enabled: true },
      { answer: 'Sipuli', origin: 'Onion', instruction: null, enabled: true },
      { answer: 'Valkosipuli', origin: 'Garlic', instruction: null, enabled: true },
      { answer: 'Porkkana', origin: 'Carrot', instruction: null, enabled: true },
      { answer: 'Tomaatti', origin: 'Tomato', instruction: null, enabled: true },
      { answer: 'Kurkku', origin: 'Cucumber', instruction: null, enabled: true },
      { answer: 'Salaatti', origin: 'Salad', instruction: null, enabled: true },
      { answer: 'Kaali', origin: 'Cabbage', instruction: null, enabled: true },
      { answer: 'Kukkakaali', origin: 'Cauliflower', instruction: null, enabled: true },
      { answer: 'Peruna', origin: 'Potato', instruction: null, enabled: true },
      { answer: 'Punajuuri', origin: 'Beetroot', instruction: null, enabled: true },
    ]
  }
}
