export default {
  ruoka: {
    name: 'Ruoka',
    langs: {
      origin: "en-GB",
      answer: "fi-FI"
    },
    questions: [
      { answer: 'Omena', origin: 'Apple', instruction: null, enabled: true },
      { answer: 'Appelsiini', origin: 'Orange', instruction: null, enabled: true },
      { answer: 'Banaani', origin: 'Banana', instruction: null, enabled: true },
      { answer: 'Sitruuna', origin: 'Lemon', instruction: null, enabled: true },
      { answer: 'Mansikka', origin: 'Strawberry', instruction: null, enabled: true },
      { answer: 'Mustikka', origin: 'Blueberry', instruction: null, enabled: true },
      { answer: 'Puolukka', origin: 'Lingonberry', instruction: null, enabled: true },
      { answer: 'Vadelma', origin: 'Raspberry', instruction: null, enabled: true },
      { answer: 'Lihatuotteet', origin: 'Meat products', instruction: null, enabled: true },
      { answer: 'Jauhliha', origin: 'Grounded meat', instruction: null, enabled: true },
      { answer: 'Kinkku', origin: 'Ham', instruction: null, enabled: true },
      { answer: 'Broileri', origin: 'Chicken', instruction: null, enabled: true },
      { answer: 'Lihapyörykkä', origin: 'Meat ball', instruction: null, enabled: true },
      { answer: 'Muna', origin: 'Egg', instruction: null, enabled: true },
      { answer: 'Keitetty muna', origin: 'Boiled egg', instruction: null, enabled: true },
      { answer: 'Paistettu muna', origin: 'Fried egg', instruction: null, enabled: true },
      { answer: 'Kananmuna', origin: 'Chicken egg', instruction: null, enabled: true },
      { answer: 'Kala', origin: 'Fish', instruction: null, enabled: true },
      { answer: 'Maitotuotteet', origin: 'Dairy products', instruction: null, enabled: true },
      { answer: 'Voi', origin: 'Butter', instruction: null, enabled: true },
      { answer: 'Margariini', origin: 'Margarine', instruction: null, enabled: true },
      { answer: 'Juusto', origin: 'Cheese', instruction: null, enabled: true },
      { answer: 'Maito', origin: 'Milk', instruction: null, enabled: true },
      { answer: 'Viljatuotteet', origin: 'Cereal products', instruction: null, enabled: true },
      { answer: 'Jauhot', origin: 'Flour', instruction: null, enabled: true },
      { answer: 'Puuro', origin: 'Porridge', instruction: null, enabled: true },
      { answer: 'Riisi', origin: 'Rice', instruction: null, enabled: true },
      { answer: 'Makaroni', origin: 'Macaroni', instruction: null, enabled: true },
      { answer: 'Leipä', origin: 'Bread', instruction: null, enabled: true },
      { answer: 'Pulla', origin: 'Sweet bun', instruction: null, enabled: true },
      { answer: 'Kakku', origin: 'Cake', instruction: null, enabled: true },
      { answer: 'Keksi', origin: 'Biscuit', instruction: null, enabled: true },
      { answer: 'Vihannekset ja Juurekset', origin: 'Vegetables and Roots', instruction: null, enabled: true },
      { answer: 'Sipuli', origin: 'Onion', instruction: null, enabled: true },
      { answer: 'Valkosipuli', origin: 'Garlic', instruction: null, enabled: true },
      { answer: 'Porkkana', origin: 'Carrot', instruction: null, enabled: true },
      { answer: 'Tomaatti', origin: 'Tomato', instruction: null, enabled: true },
      { answer: 'Kurkku', origin: 'Cucumber', instruction: null, enabled: true },
      { answer: 'Salaatti', origin: 'Salad', instruction: null, enabled: true },
      { answer: 'Kaali', origin: 'Cabbage', instruction: null, enabled: true },
      { answer: 'Kukkakaali', origin: 'Cauliflower', instruction: null, enabled: true },
      { answer: 'Peruna', origin: 'Potato', instruction: null, enabled: true },
      { answer: 'Punajuuri', origin: 'Beetroot', instruction: null, enabled: true },
    ]
  },
  ruoka_adjektiivit: {
    name: 'Ruoka adjektiivit',
    langs: {
      origin: "en-GB",
      answer: "fi-FI"
    },
    questions: [
      { origin: 'Sweet', answer: 'Makea', instruction: null, enabled: true },
      { origin: 'Sour', answer: 'Hapan', instruction: null, enabled: true },
      { origin: 'Sweet and sour', answer: 'Hapanimelä', instruction: null, enabled: true },
      { origin: 'Salty', answer: 'Suolainen', instruction: null, enabled: true },
      { origin: 'Strong', answer: 'Vahva', instruction: null, enabled: true },
      { origin: 'Mild', answer: 'Mieto', instruction: null, enabled: true },
      { origin: 'Spicy', answer: 'Tulinen', instruction: null, enabled: true },
      { origin: 'Good tasting', answer: 'Hyvänmakuinen', instruction: null, enabled: true },
      { origin: 'Bad tasting', answer: 'Pahanmakuinen', instruction: null, enabled: true },
      { origin: 'Good', answer: 'Hyvää', instruction: null, enabled: true },
      { origin: 'Bad', answer: 'Pahaa', instruction: null, enabled: true },
      { origin: 'Uncooked', answer: 'Raaka', instruction: null, enabled: true },
      { origin: 'Cooked', answer: 'Kypsä', instruction: null, enabled: true },
      { origin: 'Boiled', answer: 'Keitetty', instruction: null, enabled: true },
      { origin: 'Fried', answer: 'Paistettu', instruction: null, enabled: true },
      { origin: 'Baked', answer: 'Uunissa paistettu', instruction: null, enabled: true },
      { origin: 'Deep fried', answer: 'Friteerattu', instruction: null, enabled: true },
      { origin: 'Marinated', answer: 'Marinoitu', instruction: null, enabled: true },
      { origin: 'Hard', answer: 'Kova', instruction: null, enabled: true },
      { origin: 'Soft', answer: 'Pehmeä', instruction: null, enabled: true },
      { origin: 'Cold', answer: 'Kylmä', instruction: null, enabled: true },
      { origin: 'Warm', answer: 'Lämmin', instruction: null, enabled: true },
      { origin: 'Hot', answer: 'Kuuma', instruction: null, enabled: true },
      { origin: 'Spoiled', answer: 'Pilalla', instruction: null, enabled: true },
      { origin: 'Healthy', answer: 'Terveellinen', instruction: null, enabled: true },
      { origin: 'Unhealthy', answer: 'Epäterveellinen', instruction: null, enabled: true },
      { origin: 'Greasy', answer: 'Rasvainen', instruction: null, enabled: true },
      { origin: 'Lean', answer: 'Rasvaton', instruction: null, enabled: true }
    ]
  }
}
